[package]

name = "norn_rust"
version = "0.0.2"
authors = ["Michael Tremel <itrekkie@gmail.com>"]


# The release profile, used for `cargo build --release`
[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
